# Repository structure {#structure}

The repository contains a number of directories that serve as the framework for the model. Initially, only the `r/` and `fortran/` directories are fully populated while `fortran/` and `setup` are used for the project initialization and compilation of `hymodelc`.

```
exe/
  hymodelc
  ...
fortran/
  ...
out/
  yyyymmddHH_lati_long_zagl
    yyyymmddHH_lati_long_zagl_traj.rds
    yyyymmddHH_lati_long_zagl_foot.nc
    hymodelc
    SETUP.CFG
    CONTROL
    ...
  ...
r/
  src/
    ...
  dependencies.r
  run_stilt.r
setup
```

## exe/

Location for the compiled `hymodelc` executable as well as shared model configuration files, such as `ASCDATA.CFG`, `CONC.CFG`, `LANDUSE.ASC`, `ROUGLEN.ASC`, etc. These files are simlinked to each simulation (`out/`) directory.

## fortran/

`hymodelc` fortran source code and make file used for compilation. Compilation is most easily done with the included `setup` script (which runs as part of the standard `uataq::stilt_init()`{.r} installation) or manually with

```
cd fortran
make
mv hymodelc ../exe/hymodelc
cd ..
chmod +x exe/hymodelc
```

`permute.f90` contains a spatial permutation subroutine that applies the particle influences using variable bandwidth gaussian kernels. This is designed to be compiled as an R-compatible dynamic link library, which allows it to be used interactively within the R environment. Compilation is most easily done with the included `setup` script (which runs as part of the standard `uataq::stilt_init()` installation) or manually with

```
cd fortran
R CMD SHLIB permute.f90
mv permute.so ../r/src/permute.so
```

## out/

Initially empty, this folder propagates subdirectories with the naming convention `yyyymmddHH_lati_long_zagl` when simulations begin. See [Outputs](#outputs).


## r/

`run_stilt.r` is used to adjust model parameters, execute the simulations, and produce upstream influence footprints. See [Workflow](#workflow).

`dependencies.r` is used to load the necessary functions and packages for `run_stilt.r` and is loaded on each forked process during parallelization.

The `src/` subdirectory contains the bulk of the R source code but should not need to be modified. Each file contains a single R function with metadata documenting function arguments and usage instructions for making programatic adjustments to STILT's workflow.

