# Workflow & run_stilt.r {#workflow}

## Computational arguments

Arg       | Description
----------|-------------------------------------------------------------------------
`project` | Project name
`stilt_wd`| Working directory for the given project
`lib.loc` | Path to R package installations, passed to `library()`
`rm_dat`  | Logical indicating whether to delete `PARTICLE.DAT` after each simulation. Default to TRUE to reduce disk space since all of the trajectory information is also stored in `STILT_OUTPUT.rds` alongside the calculated upstream influence footprint
`n_nodes` | If using SLURM for job submission, number of nodes to utilize
`n_cores` | Number of cores per node to parallelize simulations by receptor locations and times
`slurm`   | Logical indicating the use of rSLURM to submit job(s)
`slurm_options` | Named list of options passed to `sbatch` using `rslurm::slurm_apply`, which typically includes `time`, `account`, and `partition` values


## Simulation timing

Arg               | Description
------------------|-------------------------------------------------------------------------
`t_start/t_end`   | Simulation timing, formatted as `'yyyy-mm-dd HH:MM:SS'` UTC
`run_times`       | Hourly simulations spanning `t_start` through `t_end`


## Receptor locations

Arg               | Description
------------------|-------------------------------------------------------------------------
`lati`            | Receptor latitude(s), in degrees. Can be a single value or a vector with length equal to `length(run_times)` of receptor latitudes
`long`            | Receptor longitude(s), in degrees. Can be a single value or a vector with length equal to `length(run_times)` of receptor longitudes
`zagl`            | Receptor height(s), in meters above ground level. Can be a single value or a vector with length equal to `length(run_times)` of receptor heights


## Meteorological data input
Arg               | Description
------------------|-------------------------------------------------------------------------
`met_directory`   | Full directory path in which ARL compatible meteorological data files can be found
`met_file_format` | `strftime` compatible file naming convention to identify meteorological data files necessary for the timing of the simulation, such as `%Y%m%d.%Hz.hrrra`. Also accepts wildcards that match regular expression patterns passed to `dir()`, such as `wrfout_d0*_jul.arl`


## Model control

Arg             | Description
----------------|-------------------------------------------------------------------------
`delt` | integration timestep [min]; if set to 0.0, then timestep is dynamically determined
`n_hours` | Number of hours to run each simulation; negative indicates backward in time
`numpar` | number of particles to be run; defaults to 200
`outdt` | interval [min] to output data to PARTICLE.DAT; defaults to 0.0, which outputs at every timestep
`run_trajec` | Logical indicating whether to produce new trajectories with `hymodelc`. If FALSE, will load the previous `STILT_OUTPUT.rds` for regridding purposes
`timeout` | number of seconds to allow hymodelc to complete before sending SIGTERM and moving to the next simulation; defaults to 3600 (1 hour)
`varsiwant` | character vector of 4-letter hymodelc variables. Options include `NULL` for all variables, or a vector containing a minimum of `c('time', 'indx', 'lati', 'long', 'zagl', 'foot')` and optionally containing 'sigw', 'tlgr', 'zsfc', 'icdx', 'temp', 'samt', 'shtf', 'tcld', 'dmas', 'dens', 'rhfr', 'sphu', 'solw', 'lcld', 'zloc', 'dswf', 'wout', 'mlht', 'rain', 'crai'


## Transport and dispersion

Arg             | Description
----------------|-------------------------------------------------------------------------
`iconvect` | flag for convection. If set to 1, then runs excessive convection as described in Gerbig et al., 2003. For specialized RAMS output, the particles will be vertically redistributed according to the output convective mass fluxes; defaults to 0
`isot` | flag used to set the isotropic turbulence option; defaults to 0 to compute horizontal turbulence from wind field deformation. Setting to 1 results in the horizontal turbulence to be the same in both the u and v directions
`mgmin` | **Needs documentation**
`ndump` | flag to dump all particle/puff points at the end of a simulation to a file called PARDUMP. This can be read at the start of a new simulation to continue the previous calculation. Valid settings include 0 (no i/o), 1 (read/write), 2 (read only), 3 (write only); defaults to 0
`nturb` | no turbulence flag; defaults to 0, which includes turbulence rather than simulating mean trajectories
`outfrac` | the fraction of the particles that are allowed to leave the model domain (given by met data); defaults to 0.9. If exceeded, the model stops
`random` | flag that tells the random number generator whether to have a different random sequence for each model run (0 - false, 1 - true); defaults to 1
`tlfrac` | the fraction of the lagrangian timescale TL to set as timestep in dispersion subroutine. The smaller this fraction is, the more finely the turbulence is resolved; defaults to 0.1
`tratio` | maximum fraction of gridcell to be travelled by a particle in a single integration timestep. This determines the timestep if DELT is set to be dynamic
`veght` | height below which a particle's time spent is tallied; defaults to 0.5, which specifies half of the PBL. Setting <=1.0 specifies a fraction of the boundary layer height, and setting >1.0 specifies a height above ground in meters
`w_option` | vertical motion calculation method. 0: use vertical velocity from data, 1: isob, 2: isen, 3: dens, 4: sigma; defaults to 0
`winderrtf` | flag that specifies whether to have particle motions be affected by horizontal wind errors; defaults to 0. If set to 1, then STILT looks for a file called "WINDERR" that has four lines: 1. Standard deviation of errors [m/s], 2. Correlation timescale of errors [min], 3. Vertical correlation lengthscale of errors [m], 4. Horizontal correlation lengthscale of errors [km]. All statistical properties are applied equally in the u and v wind components
`z_top` | top of model domain, in meters above ground level; defaults to 25000.0
`zicontroltf` | flag that specifies whether to scale the PBL heights in STILT uniformly in the entire model domain; defaults to 0. If set to 1, then STILT looks for a file called "ZICONTROL" that specifies the scaling for the PBL height. The first line indicates the number of hours that the PBL height will be changed, and each subsequent line indicates the scaling factor for that hour


## Footprint gridding

Arg             | Description
----------------|-------------------------------------------------------------------------
`xmn` | grid start longitude, in degrees from -180 to 180
`xmx` | grid end longitude, in degrees from -180 to 180
`ymn` | grid start latitude, in degrees from -180 to 180
`ymx` | grid end latitude, in degrees from -180 to 180
`xres` | resolution for longitude grid, in degrees
`yres` | resolution for latitude grid, in degrees
`time_integrate` | logical indicating whether to integrate footprint over time or retain discrete time steps


## Functionality

After turning the desired knobs from the sections above, the script symlinks the meteorological data path to the user's home directory, with the default format `paste0('m', project)`. This is done to avoid issues with paths longer than 80 characters, which will result in unsuccessful fortran simulations.

User parameters are then passed to `stilt_apply`, which chooses the appropriate function to dispatch the simulations. If using SLURM for job submission, `stilt_apply` will use the `rslurm` package to submit jobs across `n_nodes` and `n_cores` per node. If running in parallel on a single node without SLURM, `stilt_apply` will use the `parallel` package to run simulations on the current node across `n_cores`. Otherwise, `stilt_apply` will run the simulations serially using `lapply()`.




