# Outputs {#outputs}

The `out/` directory contains model parameters and outputs in subdirectories organized by receptor timing and locations. The directories are named with the convention `#_yyyymmddHH_long_lati_zagl` where

Abbreviation   | Value
---------------|----------------------------------
`#`            | Receptor index
`yyyy`         | Year (start)
`mm`           | Month (start)
`dd`           | Day (start)
`HH`           | Hour (start)
`lati`         | Receptor latitude (deg)
`long`         | Receptor longitude (deg)
`zagl`         | Receptor height above ground (m)

These directories also contain symbolic links to the files in `exe/` including the `hymodelc` executable. When the model runs trajectory simulations, diagnostic information (`hymodelc.out`) and model output (`FOOTPRINT.nc`, `STILT_OUTPUT.rds`) are also stored here.


## Footprint .rds

Footprint rasters are packaged and saved in a compressed .rds file with the naming convention `YYYYMMDDHH_LONG_LATI_ZAGL_foot.rds`. This object contains information about the model domain (accessed with `raster::extent()`), the grid resolution (accessed with `raster::res()`).

This object is structured as

```
Formal class 'RasterLayer' [package "raster"] with 12 slots
  ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. ..@ name        : chr ""
  .. .. ..@ datanotation: chr "FLT4S"
  .. .. ..@ byteorder   : chr "little"
  .. .. ..@ nodatavalue : num -3.4e+38
  .. .. ..@ NAchanged   : logi FALSE
  .. .. ..@ nbands      : int 1
  .. .. ..@ bandorder   : chr "BIL"
  .. .. ..@ offset      : int 0
  .. .. ..@ toptobottom : logi TRUE
  .. .. ..@ blockrows   : int 0
  .. .. ..@ blockcols   : int 0
  .. .. ..@ driver      : chr ""
  .. .. ..@ open        : logi FALSE
  ..@ data    :Formal class '.SingleLayerData' [package "raster"] with 13 slots
  .. .. ..@ values    : num [1:600000] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..@ offset    : num 0
  .. .. ..@ gain      : num 1
  .. .. ..@ inmemory  : logi TRUE
  .. .. ..@ fromdisk  : logi FALSE
  .. .. ..@ isfactor  : logi FALSE
  .. .. ..@ attributes: list()
  .. .. ..@ haveminmax: logi TRUE
  .. .. ..@ min       : num 0
  .. .. ..@ max       : num 0.0173
  .. .. ..@ band      : int 1
  .. .. ..@ unit      : chr ""
  .. .. ..@ names     : chr "foot"
  ..@ legend  :Formal class '.RasterLegend' [package "raster"] with 5 slots
  .. .. ..@ type      : chr(0) 
  .. .. ..@ values    : logi(0) 
  .. .. ..@ color     : logi(0) 
  .. .. ..@ names     : logi(0) 
  .. .. ..@ colortable: logi(0) 
  ..@ title   : chr(0) 
  ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. ..@ xmin: num -116
  .. .. ..@ xmax: num -110
  .. .. ..@ ymin: num 35
  .. .. ..@ ymax: num 45
  ..@ rotated : logi FALSE
  ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. ..@ geotrans: num(0) 
  .. .. ..@ transfun:function ()  
  ..@ ncols   : int 600
  ..@ nrows   : int 1000
  ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. ..@ projargs: chr "+proj=longlat +ellps=WGS84"
  ..@ history : list()
  ..@ z       : list()
```


## STILT_OUTPUT.rds

Serialized R data file that contains a list of the particle trajectories and the footprint raster. This allows regridding of the footprints without recalculating particle trajectories. Load into R with `out <- readRDS('STILT_OUTPUT.rds')`.

This object is structured as

```
List of 5
 $ runtime  : POSIXct[1:1], format: "2015-06-16"
 $ file     : chr "stilt_wd/out/1_2015061600_-111.847672_40.766189_10/STILT_OUTPUT.rds"
 $ receptor :'data.frame':	1 obs. of  4 variables:
  ..$ run_time : POSIXct[1:1], format: "2015-06-16"
  ..$ lati     : num 40.8
  ..$ long     : num -112
  ..$ zagl     : num 10
 $ particle :'data.frame':	n obs. of  29 variables:
  .. ...
```

Particle trajectory data is stored in a data frame with columns corresponding with varsiwant and can be accessed with `out$particle`. The footprint raster can be accessed with `out$footprint`. For more information about raster manipulation, the [Raster R package](https://geoscripting-wur.github.io/IntroToRaster/) is a good place to start.


