# subroutine to readin tiff format of 1kmx1km ODIAC emissions
# and return rds format with selected emissions given a lat/lon domain
# DW, update with ODIACv2017, 11/01/2017

# add missing power plant in CARVA, PP10 and PP14 in ODIAC, DW, 11/28/2017
# addTF  whether to add the missing PP in CARVA
# tiff.path, tiff format of ODIAC on lin group
# modify based on Ben's code, use rds format and flip emiss lat/lon, DW, 06/04/2018
# also, use centered lat/lon of emissions instead of lower left, match STILTv2

convert.tif2rds.odiac <- function(timestr, homedir, workdir, vname,
                                  tiff.path, addTF = F, foot.info){

  library(rgdal); library(sp); library(Hmisc)

  indir <- file.path(workdir, 'in')
  YYYY <- substr(timestr, 1, 4)
  YYMM <- substr(timestr, 3, 6)
  YYYYMM <- substr(timestr, 1, 6)
  mod <- monthDays(as.Date(paste0(YYYY, '-', substr(timestr, 5, 6), '-',
                                  substr(timestr, 7, 8))))
  minlon <- foot.info[1]; maxlon <- foot.info[2]
  minlat <- foot.info[3]; maxlat <- foot.info[4]

  # path and filename of the 1km GeoTiff ODIAC
  gzfile <- list.files(path = tiff.path, pattern = YYMM)

  # check if RData file exist, no need to unzip and convert from tiff
  rds.file <- paste0('ODIACv', vname, '_', YYYYMM, '.rds')

  if (!file.exists(file.path(indir, rds.file))) {
    cat(paste('convert.tif2rds.odiac(): working on file', gzfile, '...\n'))

    # before reading tif file, unzip it
    if (grepl('.gz', gzfile) == TRUE) {

      # always unzip to odiac directory, do not unzip to group_data
      cat('Unzipping up...\n')
      system(paste0('gunzip ', file.path(tiff.path, gzfile)))
      tiff.file <- substr(gzfile, 1, nchar(gzfile) - 3)

    } else {
      tiff.file <- gzfile
    } # end if gz

    # after reading using readGDAL, the default dimension is (y,x)
    # 21600 rows and 43200 columns
    cat('Reading tiff file.\n')
    emiss.dat <- readGDAL(file.path(tiff.path, tiff.file))

    # assign as RData file
    cat('Saving ODIAC emissions as RDS format.\n')
    saveRDS(object = emiss.dat, file = file.path(indir, rds.file))

    # finally zip up the tif file
    cat('Zipping up.\n')
    system(paste('gzip ', file.path(tiff.path, tiff.file), '.\n'))
    gc()
  } else {
    # if RDS file found, read it
      dat <- readRDS(file.path(indir, rds.file))
  } # end if

  # Centered Lat Lon, global, with 30 arcseond = 1/120 deg = 0.00833 deg res
  # 60 arcminutes in 1 degree; 60 arcseconds in 1 arcminute;
  # 1 arcsecond = 1/3600 degree
  grid    <- dat@grid
  lon.res <- grid@cellsize[1]
  lat.res <- grid@cellsize[2]

  # use centered lat/lon of emissions instead of lower left to match footprint
  # generated by STILTv2, DW, 06/04/2018
  minlon.cc <- grid@cellcentre.offset[1]
  minlat.cc <- grid@cellcentre.offset[2]
  maxlon.cc <- (grid@cells.dim[1] - 1) * lon.res + minlon.cc
  maxlat.cc <- (grid@cells.dim[2] - 1) * lon.res + minlat.cc

  # return the area map as [LON, LAT]
  cat('convert.tif2nc.odiac(): calculating the area...\n')
  emiss.lat <- seq(minlat.cc, maxlat - lat.res, lat.res)
  emiss.lon <- seq(minlon.cc, maxlon - lon.res, lon.res)
  area.co2  <- area(resolution = lon.res,
                    start.lon = min(emiss.lon), start.lat = min(emiss.lat),
                    end.lon = max(emiss.lon), end.lat = max(emiss.lat))

  # create a vector for lower left LAT LON
  lon.cc <- seq(minlon.cc, maxlon.cc, lon.res)
  lat.cc <- seq(minlat.cc, maxlat.cc, lat.res)

  # read CO2 data accordint to row first
  cat('reforming...\n')
  co2 <- matrix(dat@data$band1, nrow = 21600, byrow = TRUE)

  # flip latitude, towards increasing trend,
  # since GDAL reads from UPPER LEFT CORNER, decreasing LAT
  fco2 <- co2[length(lat.cc):1, ]
  dimnames(fco2) <- list(lat.cc, lon.cc)
  tco2 <- t(fco2)
  # now [LON, LAT]

  # grab certain region
  SEL.lat <- lat.cc >= minlat & lat.cc < maxlat
  SEL.lon <- lon.cc >= minlon & lon.cc < maxlon
  sel.co2 <- fco2[SEL.lon, SEL.lat]

  # convert the unit of CO2 emiss from Tonne Carbon/cell/month to umol/m2/s
  sel.co2 <- sel.co2 * 1E6 / 12 * 1E6 # convert tonne-C to uomol-C (= umole-CO2)
  sel.co2 <- sel.co2 / mod / 24 / 60 / 60	# convert per month to per second
  sel.co2 <- sel.co2 / area.co2		# convert per cell to per m2
  # NOW sel.co2 has unit of micromole-CO2/m2/s,
  # that can be used directly with footprint

  ### if addTF==TRUE, mannually add PP10 and PP14 in ODIAC
  if (addTF) {
    pp.lat <- 24.41796  # N
    pp.lon <- 47.01769  # E, missing power plant to the SOuth of Riyadh

    # find the nearest ODIAC 1km*1km grid
    pp.lat.index <- findInterval(pp.lat, sel.lat)
    pp.lon.index <- findInterval(pp.lon, sel.lon)
    find.lat <- sel.lat[pp.lat.index] # pp will go to 24.41667N
    find.lon <- sel.lon[pp.lon.index] # pp will go to 47.01667E

    # original emission is only ~ 182 umol/m2/s
    find.co2 <- sel.co2[pp.lon.index, pp.lat.index]

    # get area for this grid box
    find.area <- area.co2[pp.lon.index, pp.lat.index]

    # no temporal sacling factor for now
    pp.co2 <- 3.5 # an assumed 3.5MtC/yr

    # convert Mt/yr to g/yr (1E12)
    # then to mol/yr and finally to umol-C/yr (=umol-CO2/yr)
    pp.co2 <- pp.co2 * 1E6 * 1E3 * 1E3 / 12 * 1E6
    pp.co2 <- pp.co2 / 365 / 24 / 60 / 60  # convert umol-CO2/yr to umol-CO2/s
    pp.co2 <- pp.co2 /find.area            # convert umol-CO2/s to umol/m2/s
    sel.co2[pp.lon.index, pp.lat.index] <- find.co2 + pp.co2
  }

  #### storing as .RDS
  if(addTF) {
    outname <- paste0('odiac', vname, '_1kmx1km_', YYYYMM, '_', minlat,
                      '-', maxlat, 'N_', minlon, '-', maxlon, 'E_PP.rds')
  } else {
    outname <- paste0('odiac', vname, '_1kmx1km_', YYYYMM, '_', minlat,
                      '-', maxlat, 'N_', minlon, '-', maxlon, 'E.rds')
  }
  outname <- file.path(indir, outname)
  saveRDS(object = sel.co2, file = file.path(indir, outname))
  gc()

  return(sel.co2)
}
